- name: My initial setup local configuration
  hosts: localhost
  tasks:
   - name: Install packages with apt
     become: yes
     ansible.builtin.apt:
        name:
          - zsh
          - tmux
          - git
        state: present
        
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world